spring:
  datasource:
    url: jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:5432/postgres?user=postgres.cbpdizdmebasivufwuer&password=ay9KwErWITkQVReW
  jpa:
    hibernate:
      ddl-auto: update

server:
#  address: 192.168.102.28
  port: 8086